import { createAudioPlayer } from 'expo-audio';

// UI sounds. Same contract as utils/haptics.js: one word at the call site, and
// nothing here can ever throw — a device with no audio route, a player that
// failed to load or a user who muted everything must not break an interaction.
//
// Sounds are a *confirmation*, never an alert. Nothing in this app makes a
// noise the patient did not ask for by tapping something, nothing loops, and
// nothing plays on arrival at a screen. The palette is generated by
// scripts/make-sounds.js — see that file for the design notes.

const SOURCES = {
  complete: require('../../assets/sounds/complete.wav'),
  quest: require('../../assets/sounds/quest.wav'),
  checkin: require('../../assets/sounds/checkin.wav'),
  reveal: require('../../assets/sounds/reveal.wav'),
  milestone: require('../../assets/sounds/milestone.wav'),
  pop: require('../../assets/sounds/pop.wav'),
};

// Per-sound level. The generator peak-normalises each file, so this is where
// the *relative* balance lives: pop fires dozens of times a minute and has to
// sit underneath everything else.
const VOLUME = {
  complete: 0.75,
  quest: 0.6,
  checkin: 0.55,
  reveal: 0.85,
  milestone: 0.8,
  pop: 0.35,
};

const players = {};

// Mirrors the user's setting. Kept as a module-level flag rather than read from
// the store on every call, so a sound never pulls a zustand subscription into a
// hot path (pop() fires on every bubble).
let enabled = true;

export const setSoundEnabled = (value) => {
  enabled = value !== false;
};

export const isSoundEnabled = () => enabled;

function playerFor(name) {
  if (players[name]) return players[name];
  const player = createAudioPlayer(SOURCES[name]);
  player.volume = VOLUME[name] ?? 0.6;
  players[name] = player;
  return player;
}

/**
 * Warm the players at boot so the first tap is not the one that pays for
 * decoding. Failure is silent and non-fatal: a sound that never loads simply
 * never plays.
 */
export function preloadSounds() {
  Object.keys(SOURCES).forEach((name) => {
    try {
      playerFor(name);
    } catch {
      // ignore — this sound is now permanently a no-op, which is fine
    }
  });
}

function play(name) {
  if (!enabled) return;
  try {
    const player = playerFor(name);
    // Rewind before replaying: these are one-shots that can retrigger before
    // the previous tail has finished (three quests ticked quickly, a run of
    // bubbles). seekTo resolves asynchronously, so play() waits for it.
    Promise.resolve(player.seekTo(0))
      .catch(() => {})
      .then(() => {
        try {
          player.play();
        } catch {
          // ignore
        }
      });
  } catch {
    // ignore — an unplayable sound is not an error worth surfacing
  }
}

export const complete = () => play('complete');    // finished a calm exercise
export const quest = () => play('quest');          // ticked a daily quest
export const checkin = () => play('checkin');      // saved the daily check-in
export const reveal = () => play('reveal');        // the spirit animal appears
export const milestone = () => play('milestone');  // a journey milestone
export const pop = () => play('pop');              // popped a bubble

/** Release the native players. Only for teardown; the app never calls this. */
export function releaseSounds() {
  Object.values(players).forEach((player) => {
    try {
      player.remove();
    } catch {
      // ignore
    }
  });
}
